---
Name: approutes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    'api/v1/game//': 'App\Controllers\GameApiController'
    'api/v1/cards': 'App\Controllers\CardApiController'
    '': 'App\Controllers\SpaController'
